Fix missing-prototypes
plugin.c:63:1: error: no previous prototype for 'plugin_register' [-Werror=missing-prototypes]
menu.c:57:42: error: no previous prototype for 'clipman_menu_get_type' [-Werror=missing-prototypes]
menu.c:521:1: error: no previous prototype for 'clipman_menu_new' [-Werror=missing-prototypes]
collector.c:50:47: error: no previous prototype for 'clipman_collector_get_type' [-Werror=missing-prototypes]
collector.c:235:1: error: no previous prototype for 'clipman_collector_get' [-Werror=missing-prototypes]
collector.c:251:1: error: no previous prototype for 'clipman_collector_show_actions' [-Werror=missing-prototypes]
actions.c:59:45: error: no previous prototype for 'clipman_actions_get_type' [-Werror=missing-prototypes]
actions.c:908:1: error: no previous prototype for 'clipman_actions_get' [-Werror=missing-prototypes]
history.c:46:45: error: no previous prototype for 'clipman_history_get_type' [-Werror=missing-prototypes]
history.c:419:1: error: no previous prototype for 'clipman_history_get' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>